### ISSUE TITLE
N5HDF5Reader.list( path ) crashes if path is dataset

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/n5-hdf5#2]
```java
final String path = "/home/phil/Downloads/sample_A_padded_20160501.hdf";
final String dataset = "/volumes/labels/neuron_ids";
final N5HDF5Reader n5 = new N5HDF5Reader( path, 16, 16, 16 );
n5.list( dataset );
```

```
Exception in thread "main" ncsa.hdf.hdf5lib.exceptions.HDF5SymbolTableException: Symbol table:Inappropriate type ["H5Gint.c line 327 in H5G__open_name(): not a group"]
	at ch.systemsx.cisd.hdf5.hdf5lib.H5.H5Gopen(Native Method)
	at ch.systemsx.cisd.hdf5.hdf5lib.H5GLO.H5Gopen(H5GLO.java:80)
	at ch.systemsx.cisd.hdf5.HDF5.openGroup(HDF5.java:322)
	at ch.systemsx.cisd.hdf5.HDF5$10.call(HDF5.java:423)
	at ch.systemsx.cisd.hdf5.HDF5$10.call(HDF5.java:1)
	at ch.systemsx.cisd.hdf5.cleanup.CleanUpCallable.call(CleanUpCallable.java:40)
	at ch.systemsx.cisd.hdf5.HDF5.getGroupMembers(HDF5.java:436)
	at ch.systemsx.cisd.hdf5.HDF5BaseReader.getAllGroupMembers(HDF5BaseReader.java:773)
	at ch.systemsx.cisd.hdf5.HDF5BaseReader.getGroupMembers(HDF5BaseReader.java:761)
	at ch.systemsx.cisd.hdf5.HDF5ObjectReadOnlyInfoProviderHandler.getGroupMembers(HDF5ObjectReadOnlyInfoProviderHandler.java:424)
	at org.janelia.saalfeldlab.n5.hdf5.N5HDF5Reader.list(N5HDF5Reader.java:174)
	at org.janelia.saalfeldlab.paintera.N5Dummy.main(N5Dummy.java:15)
```

**Comment by axtimwalde** [comment]
Fixed with https://github.com/saalfeldlab/n5-hdf5/commit/24f4ec210b6d969ea39b16b5eca9e0f5c927d67d
