### ISSUE TITLE
Cannot close n5 container after call to `remove()`

### ISSUE THREAD

**Issue by cmhulbert** [saalfeldlab/n5-hdf5#27]
If the underlying h5 file is removed while the n5 container is open, via the `N5Writer::remove` method, then an error is thrown when trying to `N5Reader::close` the container subsequently. 

```java
hdf.hdf5lib.exceptions.HDF5AtomException: Unable to find atom information (already closed?) ["H5I.c line 1231 in H5I_dec_ref(): can't locate ID"]

	at hdf.hdf5lib.H5._H5Pclose(Native Method)
	at hdf.hdf5lib.H5.H5Pclose(H5.java:4716)
	at org.janelia.saalfeldlab.n5.hdf5.N5HDF5Util$OpenDataSetCache.close(N5HDF5Util.java:187)
	at org.janelia.saalfeldlab.n5.hdf5.N5HDF5Reader.close(N5HDF5Reader.java:719)
	at org.janelia.saalfeldlab.n5.AbstractN5Test.testRemoveContainer(AbstractN5Test.java:748)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

The issue seems to be due to an attempt to close the `opendDataSetCache`, which throws the above exception. 

To reproduce:
```java
final N5HDF5Writer n5 = new N5HDF5Writer("/tmp/removeTest.h5");
n5.remove();
n5.close();
```

**Comment by cmhulbert** [comment]
@tpietzsch I think this was introduced with #26, do you have a suggestion how to check if the `OpenDataSetCache` is already closed (after `remove()` in this case) before calling `close()`?

**Comment by tpietzsch** [comment]
@cmhulbert yes, you're right... I just added a check whether `close()` was already called...
#28

**Comment by cmhulbert** [comment]
Thanks for looking at this!
