### ISSUE TITLE
New release 2.1.1 is needed for binary compability with n5 3.1.3

### ISSUE THREAD

**Issue by ctrueden** [saalfeldlab/n5-hdf5#34]
The melting pot flagged the following problem:
```
[ERROR] Failures: 
[ERROR]   N5HDF5Test>AbstractN5Test.testReaderCreation:1115 Non-existent location throws error: unexpected exception type thrown; expected:<org.janelia.saalfeldlab.n5.N5Exception.N5IOException> but was:<java.lang.NoSuchMethodError>
[ERROR]   N5HDF5Test>AbstractN5Test.testRemoveContainer:812 unexpected exception type thrown; expected:<java.lang.Exception> but was:<java.lang.NoSuchMethodError>
```
The relevant stack trace is:
```
java.lang.NoSuchMethodError: org.janelia.saalfeldlab.n5.N5Exception$N5IOException.<init>(Ljava/lang/String;Ljava/lang/Exception;)V
	at org.janelia.saalfeldlab.n5.hdf5.N5HDF5Reader.openHdf5Reader(N5HDF5Reader.java:280)
	at org.janelia.saalfeldlab.n5.hdf5.N5HDF5Reader.<init>(N5HDF5Reader.java:209)
	at org.janelia.saalfeldlab.n5.hdf5.N5HDF5Test.createN5Reader(N5HDF5Test.java:136)
	at org.janelia.saalfeldlab.n5.AbstractN5Test.createN5Reader(AbstractN5Test.java:105)
	at org.janelia.saalfeldlab.n5.AbstractN5Test.lambda$testRemoveContainer$23(AbstractN5Test.java:812)
```

If you rebuild n5-hdf5 against n5 3.1.3, it's fine. But if you run the unit tests against the released n5-hdf5 2.1.0 binary, the above error happens. I guess some change happened between n5 3.1.2 and 3.1.3, which is backwards compatible source-wise but not binary-wise.

The fix is probably as simple as updating n5-hdf5's POM to n5 3.1.3, then cutting a new release. We will then want to bump both components simultaneously in the pom-scijava BOM.

CC @axtimwalde @bogovicj

**Comment by bogovicj** [comment]
Done
https://github.com/saalfeldlab/n5-hdf5/releases/tag/n5-hdf5-2.2.0

Includes a few other things, hence the minor version bump.
Will leave this issue open until I make a pom-scijava PR
